//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_ticket_platform.Page_User
{


    public partial class User_Event
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Image imgEvent;
        protected global::System.Web.UI.WebControls.Label lblEventName;
        protected global::System.Web.UI.WebControls.Label lblEventDescription;
        protected global::System.Web.UI.WebControls.Label lblEventTime;
        protected global::System.Web.UI.WebControls.Label lblEventLocation;
        protected global::System.Web.UI.WebControls.Label lblEventPrice;
    }
}
