//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_ticket_platform.Page_Admin
{
    public partial class Admin_Home
    {
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        /// <summary>
        /// gvOrganizations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvOrganizations;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        /// <summary>
        /// btnCreate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCreate;

        /// <summary>
        /// hdnEditId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnEditId;

        /// <summary>
        /// txtEditName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditName;

        /// <summary>
        /// txtEditEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditEmail;

        /// <summary>
        /// txtEditPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditPhone;

        /// <summary>
        /// txtEditAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditAddress;

        /// <summary>
        /// btnUpdate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdate;

        /// <summary>
        /// hdnDeleteId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnDeleteId;

        /// <summary>
        /// btnDelete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDelete;
    }
}
