//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_ticket_platform.Page_Admin.Organizer
{
    public partial class Ticket_List
    {
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        /// <summary>
        /// Content1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content Content1;

        /// <summary>
        /// Content2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content Content2;

        /// <summary>
        /// gvTickets control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvTickets;

        /// <summary>
        /// UpdatePanel1 control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;

        /// <summary>
        /// ddlEventId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEventId;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// txtPrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPrice;

        /// <summary>
        /// txtType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtType;

        /// <summary>
        /// txtTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTotal;

        /// <summary>
        /// txtStartSaleDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStartSaleDate;

        /// <summary>
        /// txtEndSaleDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEndSaleDate;

        /// <summary>
        /// chkIsActive control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIsActive;

        /// <summary>
        /// btnCreate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCreate;

        /// <summary>
        /// UpdatePanel2 control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel UpdatePanel2;

        /// <summary>
        /// hdnEditId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnEditId;

        /// <summary>
        /// ddlEditEventId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEditEventId;

        /// <summary>
        /// txtEditName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditName;

        /// <summary>
        /// txtEditPrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditPrice;

        /// <summary>
        /// txtEditType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditType;

        /// <summary>
        /// txtEditTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditTotal;

        /// <summary>
        /// txtEditStartSaleDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditStartSaleDate;

        /// <summary>
        /// txtEditEndSaleDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditEndSaleDate;

        /// <summary>
        /// chkEditIsActive control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkEditIsActive;

        /// <summary>
        /// btnUpdate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdate;

        /// <summary>
        /// UpdatePanel3 control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel UpdatePanel3;

        /// <summary>
        /// hdnDeleteId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnDeleteId;

        /// <summary>
        /// hdnForceDelete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnForceDelete;

        /// <summary>
        /// btnDelete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDelete;
    }
}
