//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_ticket_platform.Page_Admin.Organizer
{
    public partial class User_List
    {
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        /// <summary>
        /// Content1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content Content1;

        /// <summary>
        /// Content2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content Content2;

        /// <summary>
        /// gvUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvUsers;

        /// <summary>
        /// UpdatePanel1 control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// ddlRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRole;

        /// <summary>
        /// chkIsVerified control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIsVerified;

        /// <summary>
        /// btnCreate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCreate;

        /// <summary>
        /// UpdatePanel2 control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel UpdatePanel2;

        /// <summary>
        /// hdnEditId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnEditId;

        /// <summary>
        /// txtEditEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditEmail;

        /// <summary>
        /// txtEditName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditName;

        /// <summary>
        /// txtEditPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditPhone;

        /// <summary>
        /// ddlEditRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEditRole;

        /// <summary>
        /// chkEditIsVerified control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkEditIsVerified;

        /// <summary>
        /// btnUpdate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdate;

        /// <summary>
        /// UpdatePanel3 control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel UpdatePanel3;

        /// <summary>
        /// hdnDeleteId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnDeleteId;

        /// <summary>
        /// btnDelete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDelete;
    }
}
