//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_ticket_platform.Page_User.Controls.User_Home
{
    public partial class EventCarte
    {
        protected global::System.Web.UI.HtmlControls.HtmlImage imgEventBanner;
        protected global::System.Web.UI.HtmlControls.HtmlImage imgEventBannerBg;
        protected global::System.Web.UI.WebControls.Label lblTicketCount;
        protected global::System.Web.UI.WebControls.Label lblEventTitle;
        protected global::System.Web.UI.WebControls.Label lblEventDate;
        protected global::System.Web.UI.WebControls.Label lblEventLocation;
        protected global::System.Web.UI.WebControls.HyperLink lnkDetail;
        protected global::System.Web.UI.WebControls.Repeater TicketTypesRepeater;
    }
}
