//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_ticket_platform.Page_User.Controls
{
    public partial class Footer
    {
        /// <summary>
        /// CopyrightYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label CopyrightYear;

        /// <summary>
        /// SocialLinks control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl SocialLinks;

        /// <summary>
        /// QuickLinks control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl QuickLinks;

        /// <summary>
        /// SupportLinks control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl SupportLinks;
    }
}
