//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_ticket_platform.Page_User.Controls
{
    public partial class Navbar
    {
        /// <summary>
        /// MainMenu control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl MainMenu;

        /// <summary>
        /// MobileMenuButton control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton MobileMenuButton;

        /// <summary>
        /// MobileMenu control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl MobileMenu;
    }
}
