//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_ticket_platform.Page_Admin.Controls
{
    public partial class sidebar
    {
        /// <summary>
        /// Form control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
