//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_ticket_platform.Page_User.Controls
{
    public partial class Sidebar
    {
        /// <summary>
        /// UserAvatar control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlImage UserAvatar;

        /// <summary>
        /// UserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label UserName;

        /// <summary>
        /// UserEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label UserEmail;

        /// <summary>
        /// NavigationMenu control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl NavigationMenu;

        /// <summary>
        /// AccountSettings control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AccountSettings;
    }
}
