//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrietPhamShopWeb.Adminpage
{


    public partial class ManageProducts
    {

        /// <summary>
        /// gvProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvProducts;

        /// <summary>
        /// txtProductName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtProductName;

        /// <summary>
        /// txtPrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPrice;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        /// <summary>
        /// ddlCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        /// <summary>
        /// txtStock.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStock;

        /// <summary>
        /// hdnProductId.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnProductId;


        /// <summary>
        /// btnAdd control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAdd;

        /// <summary>
        /// btnUpdate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdate;

        /// <summary>
        /// btnDelete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDelete;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// FileUpload1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload FileUpload1;

        /// <summary>
        /// preview1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image preview1;

        /// <summary>
        /// FileUpload2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload FileUpload2;

        /// <summary>
        /// preview2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image preview2;

        /// <summary>
        /// FileUpload3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload FileUpload3;

        /// <summary>
        /// preview3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image preview3;
    }
}
