//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrietPhamShopWeb.Adminpage
{
    public partial class ManageProducts
    {
        /// <summary>
        /// btnAddProduct control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddProduct;

        /// <summary>
        /// gvProducts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvProducts;
    }
} 