//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrietPhamShopWeb.Adminpage
{
    public partial class ManageUser
    {
        /// <summary>
        /// Content1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content Content1;

        /// <summary>
        /// gvUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvUsers;
    }
}
