//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrietPhamShopWeb.Controls
{
    public partial class Footer
    {
        /// <summary>
        /// lnkFooterHome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkFooterHome;

        /// <summary>
        /// lnkFooterProducts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkFooterProducts;

        /// <summary>
        /// lnkFooterAbout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkFooterAbout;

        /// <summary>
        /// lnkFooterContact control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkFooterContact;
    }
}
